### PR TITLE
Restructured the project

### PR DESCRIPTION
**Pull request by imjaypatel12**
To make it an installable package. User can now `pip install` this package and use it.

Here are the details in brief:
1. `examples` dir is excluded from the main `pylog` package
2. `setup.py` is added with required details (e.g. license, name, desc, authoring) in it to make the package installable. (PLEASE REVIEW IT)
3. `examples` is taken out and placed under the root of the repo. All the examples now reference to the `pylog` to use its features

### CODE REVIEW

**Comment by RussAbbott** [comment]
Let's talk about all this when we get together. I'm really an amateur on
GitHub.

**Comment by imjaypatel12** [comment]
This pull request now include following in addition to the previous changes:

1. Resolved merge conflicts. It is now safe to merge this pull request into your master.
2. Added pytest support, integrated it with setup.py of the package
3. Restructured the core library/package project to adhere the standard. Placed dev files in `src` and tests in `tests` directory
4. Updated setup.py, added required dependencies for `pylog` to work. Added several configuration files. Added meta-infos like classifiers and keywords for this library project.
5. Updated README.

At this point, you can go to `<root>/pylog` and run `python setup.py test`. This will install the `pylog` as a package in the system and then will run all the tests placed within `<root>/pylog/tests/`.

You can find additional setup details at [imjaypatel12/pylog/pylog](https://github.com/imjaypatel12/pylog/tree/master/pylog).

**Comment by dougransom** [comment]
@RussAbbott are you going to accept the PR?  To me it is a move in the right direction, I was thinking I would also like a installable package, makes it so much easier for local editing.  I was thinking of doing the same as @imjaypatel12  before I noticed this PR. If you accept this PR I will probably tweak the install to us pyproject.toml in favor of  setup.py  as packages are moving in that detection.

**Comment by dougransom** [comment]
I prefer the examples to be in the src/pylog/examples folder so someone who doesn't install from src can look in their system to find the examples and review them.

**Comment by RussAbbott** [comment]
Hi Doug,

You seem to know what you're doing. What should I do so that you can
upgrade the pylog repo to current standards? (As I said, I haven't touched
any of this in years.)

I notice that you're professionally interested in investments. I do a fair
amount of option trading. Do you work in that area?

-- Russ Abbott
Professor Emeritus, Computer Science
California State University, Los Angeles

**Pull request merged**
